### PR TITLE
[BDHK-188] Improve Logging across board

### PR DESCRIPTION
**Pull request by adelowo**
f1a586bdc9228f7b5e66bda3965f50339e543a16 has been cherrypicked from `testnet` branch as 
it fixes the multi env deployment issue.

I have also used the `debug mode` config value to toggle between error and info state for the logs
instead of using a new config value. if true, info logs will be printed, if false, only errors will be printed.

All dangling `fmt.Print`s have been replaced too

### CODE REVIEW

**Review by blewater — APPROVED** [review]
LGTM

**Comment by blewater** [comment]
@adelowo shouldn't the integration tests run?

**Comment by adelowo** [comment]
> @adelowo shouldn't the integration tests run?

We are yet to approve and merge #16. We only did it on the solver side

**Comment by adelowo** [comment]
#16 is merged now

**Pull request merged**
